#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XuLy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDia")]
	public partial class QuanlidiaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietThueTra(ChiTietThueTra instance);
    partial void UpdateChiTietThueTra(ChiTietThueTra instance);
    partial void DeleteChiTietThueTra(ChiTietThueTra instance);
    partial void InsertDVD_CD(DVD_CD instance);
    partial void UpdateDVD_CD(DVD_CD instance);
    partial void DeleteDVD_CD(DVD_CD instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiDia(LoaiDia instance);
    partial void UpdateLoaiDia(LoaiDia instance);
    partial void DeleteLoaiDia(LoaiDia instance);
    partial void InsertTieuDe(TieuDe instance);
    partial void UpdateTieuDe(TieuDe instance);
    partial void DeleteTieuDe(TieuDe instance);
    partial void InsertTTDatDia(TTDatDia instance);
    partial void UpdateTTDatDia(TTDatDia instance);
    partial void DeleteTTDatDia(TTDatDia instance);
    partial void InsertTTThueDia(TTThueDia instance);
    partial void UpdateTTThueDia(TTThueDia instance);
    partial void DeleteTTThueDia(TTThueDia instance);
    #endregion
		
		public QuanlidiaDataContext() : 
				base(global::XuLy.Properties.Settings.Default.QLDiaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlidiaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlidiaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlidiaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanlidiaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietThueTra> ChiTietThueTras
		{
			get
			{
				return this.GetTable<ChiTietThueTra>();
			}
		}
		
		public System.Data.Linq.Table<DVD_CD> DVD_CDs
		{
			get
			{
				return this.GetTable<DVD_CD>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDia> LoaiDias
		{
			get
			{
				return this.GetTable<LoaiDia>();
			}
		}
		
		public System.Data.Linq.Table<TieuDe> TieuDes
		{
			get
			{
				return this.GetTable<TieuDe>();
			}
		}
		
		public System.Data.Linq.Table<TTDatDia> TTDatDias
		{
			get
			{
				return this.GetTable<TTDatDia>();
			}
		}
		
		public System.Data.Linq.Table<TTThueDia> TTThueDias
		{
			get
			{
				return this.GetTable<TTThueDia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietThueTra")]
	public partial class ChiTietThueTra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuThue;
		
		private string _MaDia;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private System.Nullable<double> _PhiTreHan;
		
		private EntityRef<DVD_CD> _DVD_CD;
		
		private EntityRef<TTThueDia> _TTThueDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuThueChanging(string value);
    partial void OnMaPhieuThueChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnPhiTreHanChanging(System.Nullable<double> value);
    partial void OnPhiTreHanChanged();
    #endregion
		
		public ChiTietThueTra()
		{
			this._DVD_CD = default(EntityRef<DVD_CD>);
			this._TTThueDia = default(EntityRef<TTThueDia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThue", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuThue
		{
			get
			{
				return this._MaPhieuThue;
			}
			set
			{
				if ((this._MaPhieuThue != value))
				{
					if (this._TTThueDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThue = value;
					this.SendPropertyChanged("MaPhieuThue");
					this.OnMaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					if (this._DVD_CD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiTreHan", DbType="Float")]
		public System.Nullable<double> PhiTreHan
		{
			get
			{
				return this._PhiTreHan;
			}
			set
			{
				if ((this._PhiTreHan != value))
				{
					this.OnPhiTreHanChanging(value);
					this.SendPropertyChanging();
					this._PhiTreHan = value;
					this.SendPropertyChanged("PhiTreHan");
					this.OnPhiTreHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVD_CD_ChiTietThueTra", Storage="_DVD_CD", ThisKey="MaDia", OtherKey="MaDia", IsForeignKey=true)]
		public DVD_CD DVD_CD
		{
			get
			{
				return this._DVD_CD.Entity;
			}
			set
			{
				DVD_CD previousValue = this._DVD_CD.Entity;
				if (((previousValue != value) 
							|| (this._DVD_CD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DVD_CD.Entity = null;
						previousValue.ChiTietThueTras.Remove(this);
					}
					this._DVD_CD.Entity = value;
					if ((value != null))
					{
						value.ChiTietThueTras.Add(this);
						this._MaDia = value.MaDia;
					}
					else
					{
						this._MaDia = default(string);
					}
					this.SendPropertyChanged("DVD_CD");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTThueDia_ChiTietThueTra", Storage="_TTThueDia", ThisKey="MaPhieuThue", OtherKey="MaPhieuThue", IsForeignKey=true)]
		public TTThueDia TTThueDia
		{
			get
			{
				return this._TTThueDia.Entity;
			}
			set
			{
				TTThueDia previousValue = this._TTThueDia.Entity;
				if (((previousValue != value) 
							|| (this._TTThueDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TTThueDia.Entity = null;
						previousValue.ChiTietThueTras.Remove(this);
					}
					this._TTThueDia.Entity = value;
					if ((value != null))
					{
						value.ChiTietThueTras.Add(this);
						this._MaPhieuThue = value.MaPhieuThue;
					}
					else
					{
						this._MaPhieuThue = default(string);
					}
					this.SendPropertyChanged("TTThueDia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DVD_CD")]
	public partial class DVD_CD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDia;
		
		private string _MoTa;
		
		private string _Status;
		
		private System.Nullable<double> _Gia;
		
		private string _MaTieuDe;
		
		private EntitySet<ChiTietThueTra> _ChiTietThueTras;
		
		private EntitySet<TTDatDia> _TTDatDias;
		
		private EntityRef<TieuDe> _TieuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    #endregion
		
		public DVD_CD()
		{
			this._ChiTietThueTras = new EntitySet<ChiTietThueTra>(new Action<ChiTietThueTra>(this.attach_ChiTietThueTras), new Action<ChiTietThueTra>(this.detach_ChiTietThueTras));
			this._TTDatDias = new EntitySet<TTDatDia>(new Action<TTDatDia>(this.attach_TTDatDias), new Action<TTDatDia>(this.detach_TTDatDias));
			this._TieuDe = default(EntityRef<TieuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(150)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVD_CD_ChiTietThueTra", Storage="_ChiTietThueTras", ThisKey="MaDia", OtherKey="MaDia")]
		public EntitySet<ChiTietThueTra> ChiTietThueTras
		{
			get
			{
				return this._ChiTietThueTras;
			}
			set
			{
				this._ChiTietThueTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVD_CD_TTDatDia", Storage="_TTDatDias", ThisKey="MaDia", OtherKey="MaDia")]
		public EntitySet<TTDatDia> TTDatDias
		{
			get
			{
				return this._TTDatDias;
			}
			set
			{
				this._TTDatDias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_DVD_CD", Storage="_TieuDe", ThisKey="MaTieuDe", OtherKey="MaTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.DVD_CDs.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.DVD_CDs.Add(this);
						this._MaTieuDe = value.MaTieuDe;
					}
					else
					{
						this._MaTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThueTras(ChiTietThueTra entity)
		{
			this.SendPropertyChanging();
			entity.DVD_CD = this;
		}
		
		private void detach_ChiTietThueTras(ChiTietThueTra entity)
		{
			this.SendPropertyChanging();
			entity.DVD_CD = null;
		}
		
		private void attach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.DVD_CD = this;
		}
		
		private void detach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.DVD_CD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _Address;
		
		private EntitySet<TTDatDia> _TTDatDias;
		
		private EntitySet<TTThueDia> _TTThueDias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
		
		public KhachHang()
		{
			this._TTDatDias = new EntitySet<TTDatDia>(new Action<TTDatDia>(this.attach_TTDatDias), new Action<TTDatDia>(this.detach_TTDatDias));
			this._TTThueDias = new EntitySet<TTThueDia>(new Action<TTThueDia>(this.attach_TTThueDias), new Action<TTThueDia>(this.detach_TTThueDias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(90)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TTDatDia", Storage="_TTDatDias", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<TTDatDia> TTDatDias
		{
			get
			{
				return this._TTDatDias;
			}
			set
			{
				this._TTDatDias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TTThueDia", Storage="_TTThueDias", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<TTThueDia> TTThueDias
		{
			get
			{
				return this._TTThueDias;
			}
			set
			{
				this._TTThueDias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_TTThueDias(TTThueDia entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_TTThueDias(TTThueDia entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDia")]
	public partial class LoaiDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<TieuDe> _TieuDes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LoaiDia()
		{
			this._TieuDes = new EntitySet<TieuDe>(new Action<TieuDe>(this.attach_TieuDes), new Action<TieuDe>(this.detach_TieuDes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(150)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_TieuDe", Storage="_TieuDes", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<TieuDe> TieuDes
		{
			get
			{
				return this._TieuDes;
			}
			set
			{
				this._TieuDes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TieuDes(TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = this;
		}
		
		private void detach_TieuDes(TieuDe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TieuDe")]
	public partial class TieuDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTieuDe;
		
		private string _TenTieuDe;
		
		private string _MaLoai;
		
		private EntitySet<DVD_CD> _DVD_CDs;
		
		private EntitySet<TTDatDia> _TTDatDias;
		
		private EntityRef<LoaiDia> _LoaiDia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    partial void OnTenTieuDeChanging(string value);
    partial void OnTenTieuDeChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    #endregion
		
		public TieuDe()
		{
			this._DVD_CDs = new EntitySet<DVD_CD>(new Action<DVD_CD>(this.attach_DVD_CDs), new Action<DVD_CD>(this.detach_DVD_CDs));
			this._TTDatDias = new EntitySet<TTDatDia>(new Action<TTDatDia>(this.attach_TTDatDias), new Action<TTDatDia>(this.detach_TTDatDias));
			this._LoaiDia = default(EntityRef<LoaiDia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTieuDe", DbType="NVarChar(70)")]
		public string TenTieuDe
		{
			get
			{
				return this._TenTieuDe;
			}
			set
			{
				if ((this._TenTieuDe != value))
				{
					this.OnTenTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TenTieuDe = value;
					this.SendPropertyChanged("TenTieuDe");
					this.OnTenTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LoaiDia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_DVD_CD", Storage="_DVD_CDs", ThisKey="MaTieuDe", OtherKey="MaTieuDe")]
		public EntitySet<DVD_CD> DVD_CDs
		{
			get
			{
				return this._DVD_CDs;
			}
			set
			{
				this._DVD_CDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_TTDatDia", Storage="_TTDatDias", ThisKey="MaTieuDe", OtherKey="MaTieuDe")]
		public EntitySet<TTDatDia> TTDatDias
		{
			get
			{
				return this._TTDatDias;
			}
			set
			{
				this._TTDatDias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDia_TieuDe", Storage="_LoaiDia", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public LoaiDia LoaiDia
		{
			get
			{
				return this._LoaiDia.Entity;
			}
			set
			{
				LoaiDia previousValue = this._LoaiDia.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDia.Entity = null;
						previousValue.TieuDes.Remove(this);
					}
					this._LoaiDia.Entity = value;
					if ((value != null))
					{
						value.TieuDes.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("LoaiDia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DVD_CDs(DVD_CD entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_DVD_CDs(DVD_CD entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
		
		private void attach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = this;
		}
		
		private void detach_TTDatDias(TTDatDia entity)
		{
			this.SendPropertyChanging();
			entity.TieuDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTDatDia")]
	public partial class TTDatDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDatDia;
		
		private System.Nullable<System.DateTime> _NgayDat;
		
		private string _MaKH;
		
		private string _MaDia;
		
		private string _MaTieuDe;
		
		private EntityRef<DVD_CD> _DVD_CD;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<TieuDe> _TieuDe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDatDiaChanging(string value);
    partial void OnMaDatDiaChanged();
    partial void OnNgayDatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDatChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnMaDiaChanging(string value);
    partial void OnMaDiaChanged();
    partial void OnMaTieuDeChanging(string value);
    partial void OnMaTieuDeChanged();
    #endregion
		
		public TTDatDia()
		{
			this._DVD_CD = default(EntityRef<DVD_CD>);
			this._KhachHang = default(EntityRef<KhachHang>);
			this._TieuDe = default(EntityRef<TieuDe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDatDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDatDia
		{
			get
			{
				return this._MaDatDia;
			}
			set
			{
				if ((this._MaDatDia != value))
				{
					this.OnMaDatDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDatDia = value;
					this.SendPropertyChanged("MaDatDia");
					this.OnMaDatDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDat", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDat
		{
			get
			{
				return this._NgayDat;
			}
			set
			{
				if ((this._NgayDat != value))
				{
					this.OnNgayDatChanging(value);
					this.SendPropertyChanging();
					this._NgayDat = value;
					this.SendPropertyChanged("NgayDat");
					this.OnNgayDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDia", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaDia
		{
			get
			{
				return this._MaDia;
			}
			set
			{
				if ((this._MaDia != value))
				{
					if (this._DVD_CD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaChanging(value);
					this.SendPropertyChanging();
					this._MaDia = value;
					this.SendPropertyChanged("MaDia");
					this.OnMaDiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTieuDe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaTieuDe
		{
			get
			{
				return this._MaTieuDe;
			}
			set
			{
				if ((this._MaTieuDe != value))
				{
					if (this._TieuDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTieuDeChanging(value);
					this.SendPropertyChanging();
					this._MaTieuDe = value;
					this.SendPropertyChanged("MaTieuDe");
					this.OnMaTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DVD_CD_TTDatDia", Storage="_DVD_CD", ThisKey="MaDia", OtherKey="MaDia", IsForeignKey=true)]
		public DVD_CD DVD_CD
		{
			get
			{
				return this._DVD_CD.Entity;
			}
			set
			{
				DVD_CD previousValue = this._DVD_CD.Entity;
				if (((previousValue != value) 
							|| (this._DVD_CD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DVD_CD.Entity = null;
						previousValue.TTDatDias.Remove(this);
					}
					this._DVD_CD.Entity = value;
					if ((value != null))
					{
						value.TTDatDias.Add(this);
						this._MaDia = value.MaDia;
					}
					else
					{
						this._MaDia = default(string);
					}
					this.SendPropertyChanged("DVD_CD");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TTDatDia", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.TTDatDias.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.TTDatDias.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TieuDe_TTDatDia", Storage="_TieuDe", ThisKey="MaTieuDe", OtherKey="MaTieuDe", IsForeignKey=true)]
		public TieuDe TieuDe
		{
			get
			{
				return this._TieuDe.Entity;
			}
			set
			{
				TieuDe previousValue = this._TieuDe.Entity;
				if (((previousValue != value) 
							|| (this._TieuDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TieuDe.Entity = null;
						previousValue.TTDatDias.Remove(this);
					}
					this._TieuDe.Entity = value;
					if ((value != null))
					{
						value.TTDatDias.Add(this);
						this._MaTieuDe = value.MaTieuDe;
					}
					else
					{
						this._MaTieuDe = default(string);
					}
					this.SendPropertyChanged("TieuDe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTThueDia")]
	public partial class TTThueDia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuThue;
		
		private System.Nullable<System.DateTime> _NgayThue;
		
		private System.Nullable<double> _Cost;
		
		private string _MaKH;
		
		private EntitySet<ChiTietThueTra> _ChiTietThueTras;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuThueChanging(string value);
    partial void OnMaPhieuThueChanged();
    partial void OnNgayThueChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThueChanged();
    partial void OnCostChanging(System.Nullable<double> value);
    partial void OnCostChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public TTThueDia()
		{
			this._ChiTietThueTras = new EntitySet<ChiTietThueTra>(new Action<ChiTietThueTra>(this.attach_ChiTietThueTras), new Action<ChiTietThueTra>(this.detach_ChiTietThueTras));
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuThue", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuThue
		{
			get
			{
				return this._MaPhieuThue;
			}
			set
			{
				if ((this._MaPhieuThue != value))
				{
					this.OnMaPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuThue = value;
					this.SendPropertyChanged("MaPhieuThue");
					this.OnMaPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThue", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThue
		{
			get
			{
				return this._NgayThue;
			}
			set
			{
				if ((this._NgayThue != value))
				{
					this.OnNgayThueChanging(value);
					this.SendPropertyChanging();
					this._NgayThue = value;
					this.SendPropertyChanged("NgayThue");
					this.OnNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Float")]
		public System.Nullable<double> Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTThueDia_ChiTietThueTra", Storage="_ChiTietThueTras", ThisKey="MaPhieuThue", OtherKey="MaPhieuThue")]
		public EntitySet<ChiTietThueTra> ChiTietThueTras
		{
			get
			{
				return this._ChiTietThueTras;
			}
			set
			{
				this._ChiTietThueTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_TTThueDia", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.TTThueDias.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.TTThueDias.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietThueTras(ChiTietThueTra entity)
		{
			this.SendPropertyChanging();
			entity.TTThueDia = this;
		}
		
		private void detach_ChiTietThueTras(ChiTietThueTra entity)
		{
			this.SendPropertyChanging();
			entity.TTThueDia = null;
		}
	}
}
#pragma warning restore 1591
